#113 use std.experimental.logger
mysql-d/mysql-native pull request #187
Opened 2018-05-13 20:52 UTC by SingingBush

not a lot to it but should be helpful

2018-05-14 02:07 UTC, Abscissa commented on .gitignore
> +# Ignore Intellij IDE files:
These changes aren't related to to the rest of the pull request and shouldn't be part of the same PR.

Also, these files being ignored aren't related to mysql-native or any of its dependencies. Instead, they are editor-specific and thus user-specific, so they belong in the user's own local ignore file (`.git/info/exclude`) not in the project's public `.gitignore`. (I do wish git and common git tutorials were more clear about this, though.)

2018-05-14 02:51 UTC, Abscissa commented
A few things with this:

1. mysql-native shouldn't output anything to stdout/stderr by default. This needs to be opt-in.
2. The logger should be configurable, not hard-wired to phobos's default of FileLogger(stderr).
3. Since the phobos logger is experimental, it's probably best to have it all behind a -version= identifier.

I'd stick all logging-calls and logging-related everything behind a `version(MySQLNLog)`. So it's only compiled-in and used when its requested (and to prevent any future changes in the experimental API from breaking mysql-native).

And then there should be a small mysql.log module containing a public `version(MySQLNLog) Logger logger;` which the user can configure as they wish (it should also be compiled in when `version(MySQLDocs)` is defined so it's included in the generated documentation). Either default it to FileLogger(stderr) or better yet, leave it null by default (so it doesn't need a module constructor - those can be problematic...I kinda wish that module wasn't OO-based) and force the user to set it to what they want before using mysql-native.

FYI, the current travis-ci test failures appear to be unrelated to this, and no cause for concern. There's some kind of [hiccup](https://github.com/travis-ci/travis-ci/issues/9613) currently causing travis-ci issues with certain compiler versions.

2018-05-14 08:56 UTC, SingingBush commented on .gitignore
> +# Ignore Intellij IDE files:
that's fair enough, I'll remove them. I prefer keeping IDE related ignores in my projects gitignore. The more people that contribute the more chance there is that someone won't have a user specific ignore and such files may get pushed.

2018-05-14 09:43 UTC, SingingBush commented
1. I agree that the default should be not to log anything. This seems like a defect of std.experimental.logger, it has a _nulllogger_ but for some reason the default is the filelogger. It should be down to users to chose which is used though. This is done via _sharedLog_, it should be configured by users of mysql-native.
2. It is configurable, users should make an implementation of _Logger_ and assign it to _sharedLog_. Then any dependency that's using std.experimental.logger will output to the same Logger.
3. How about using a static if with a `__VERSION__`?

2018-05-16 03:46 UTC, Abscissa commented
>1. I agree that the default should be not to log anything. This seems like a defect of std.experimental.logger ([created issue for it](https://issues.dlang.org/show_bug.cgi?id=18857)), it has a _nulllogger_ but for some reason the default is the filelogger. It should be down to users to chose which is used though. This is done via _sharedLog_, it should be configured by users of mysql-native.
>2. It is configurable, users should make an implementation of _Logger_ and assign it to _sharedLog_. Then any dependency that's using std.experimental.logger will output to the same Logger.

Oh, I see. This confused me until I realized sharedLog was something already-existing in  std.experimental.logger.core. I didn't notice it there before. I understand now.

>3. How about using a static if with a `__VERSION__`?
> or: __traits(compiles, 

I was thinking more of a user's-choice opt-in, regardless of version. Most importantly, so that anyone not already using std.experimental.logger doesn't get stdout/err output from mysqln without asking for it. But also just as an escape hatch in case, for example, if any API changes occur in a future logger release, or for any other unforeseeable reason.

2019-10-28 07:36 UTC, SingingBush commented
Now that this has been revised and shown to pass CI can it be merged or are further changes required?

2019-10-28 23:42 UTC, schveiguy commented
Does this jive with vibed's logging system?

2019-10-28 23:45 UTC, schveiguy commented
Hm.. wait, it's not logging to vibe-d's log system in the other parts, only in socket creation. Is there a way to make this seamless?

2019-10-28 23:47 UTC, schveiguy commented on source/mysql/protocol/comms.d
> +
Something that might be useful is to make an abstracted logging facility (to define either vibe-d or std.experimental logging). Just create functions or alias the appropriate logging facility, and then your code doesn't have to have any static ifs.

2019-10-31 20:15 UTC, Abscissa commented
This will definitely be a nice feature to have.

Here are the things still needed:

A. All the instances of `static if(__traits(compiles, (){ import std.experimental.logger; } ))` should be changed to `version(MYSQLN_LOG)`. Since Phobos’s `sharedLog` defaults to a non-null logger, we need to be opt-in, not opt-out.

B. Everything should be logged to the same logger, not some things to the phobos logger and other things to vibe logger. Probably the easiest thing would be to just change that one place where it’s using the vibe logger and just change that to the phobos logger instead.

If you do want to support the vibe logger as well, then like @schveiguy suggested, there should be a single abstracted logging facility which can then be directed to either phobos logging, vibe logging or whatever else there might be. But, doing that would be a more involved change...which will involve more code review...so if you did want to do that, I’d recommend leaving it as a separate follow-up PR after this one, so we can at least get this phobos logging support up-and-running in the meantime.

C. To make sure this gets compiled-checked by CI, `dub.sdl` should be updated to add `versions “MYSQLN_LOG”` to the configurations `unittest-vibe` and `unittest-vibe-ut` (this is for the vibe socket tests). Similary, for the phobos socket tests, add `-version=MYSQLN_LOG` to [this line](https://github.com/mysql-d/mysql-native/blob/master/run_tests.d#L236). And finally, because I don’t want it to clutter the test output (just have it compile-checked), add this to `source/mysql/test/common.d` somewhere inside the big `version(DoCoreTests) {...}` section:

```d
version(MYSQLN_LOG)
static this()
{
	import std.experimental.logger;
	// Or whatever is the correct syntax for this:
	sharedLog = nullLogger;
}
```

With these changes, we should be good-to-go.

2019-10-31 20:22 UTC, Abscissa commented
Oh, also: Should we be prefixing something like `"mysql-native: "` to each of our log outputs, or does std.experimental.logger automatically prepend the module name?

2019-11-01 13:19 UTC, schveiguy commented
> If you do want to support the vibe logger as well

Please support vibe-d logger. I want one logging system in my vibe-d app. If this doesn't happen, I'll fix it myself ;)

Question: is it possible for std.experimental.logger to support vibe-d logging seamlessly? Might be the best option.

And I really do want to see some logging in mysql, would be super-useful.

2019-11-01 22:39 UTC, SingingBush commented
You can get vibe log and std logger working together, I have both types working for me. There's no need to prefix, the output shows where the log messages come from. The reason I put a vibe log in one section was because it was vibed specific code so made sense to do so.

I'm happy to make the changes. Just not sure how soon it will be.

2021-01-23 15:55 UTC, schveiguy commented
Related: #113

2021-05-24 20:47 UTC, SingingBush commented
This is rebased and thanks to CI proved to not cause any issues. I appreciate there were some comments about alternative approaches but seeing as no alternatives have implemented in the last 3 years can this be merged in the meantime. 

In the current form, I don't believe it will cause anyone issues and even if it did it's a small piece to revert. Having those prepared statements output in my application would have certainly helped me in the last few years. Users are already 'opting in' when they decide to configure a logger.

2021-05-28 16:15 UTC, schveiguy commented
Ugh, I thought adding "edited" to the trigger for PRs would rerun the actions when master is merged. Is there a way to get this to rerun automatically?

2021-05-28 16:23 UTC, schveiguy commented
Looks like it's not possible. That's unfortunate. So basically, GH actions are stale as soon as another PR is merged. https://github.community/t/re-build-pr-if-target-branch-is-changed/17588

2021-05-28 16:34 UTC, schveiguy requested changes
Add vibe logging alongside std.experimental.logger. My thoughts for first release is to use vibe logging facilities by default if `Have_vibe_core`, and otherwise use `std.experimental.logger`. Configuration of which logging facility to use via a version/config in the dub.sdl is acceptable, but not necessary for this. But absolutely, if you are on vibe, you should not have to forego logging.

Open to other ideas, but if we are going to start adding logging, let's support the mechanism the user has already selected.

2021-05-28 16:34 UTC, schveiguy commented on source/mysql/connection.d
> +}
Let's make this either a `version` or an `enum` that can be used with `static if`. Seeing this all throughout the code shouldn't be necessary.

2021-05-28 16:52 UTC, schveiguy commented on source/mysql/protocol/comms.d
> +			sharedLog.errorf("packet error: %s %s", okp.error, okp.message);
Shouldn't this be behind a check to make sure it's actually an error? or am I missing something.

2021-05-28 16:58 UTC, SingingBush commented on source/mysql/protocol/comms.d
> +			sharedLog.errorf("packet error: %s %s", okp.error, okp.message);
ok will make some changes. Should have another commit soon

2021-05-28 16:59 UTC, schveiguy commented
FYI, I'm seeing the trace messages in the CI logs. Why are those being triggered? I don't want people who have standard debug flags to see all the trace data.

2021-05-28 17:36 UTC, SingingBush commented
> By default, the logger will log ALL messages. This is unacceptable for mysql-native to use. Everyone who uses mysql-native will all of a sudden see mountains of trace messages appear.
> 
> This is unfortunately a design issue IMO of std.experimental.logger and not anything you can do here, but nevertheless, we can't accept this without a version switch.

Are you seeing that because running tests will set it into trace level? I use `std.experimental.logger` and certainly don't get all levels of logging being output.

2021-05-28 17:38 UTC, schveiguy commented
No, I'm saying that if you NEVER do anything to use std.experimental.logger, but used mysql-native with this PR, you will get tracing data on stderr.

See my latest post to the NG: https://forum.dlang.org/post/s8r9ac$hlt$1@digitalmars.com

2021-05-28 17:42 UTC, schveiguy commented
Another option is not to use sharedLog, but use a library-specific logger instance (which of course, could be set to the same as sharedLog).

2021-05-29 01:45 UTC, schveiguy commented
I'll do a release now, without this PR yet, just to get people up and running.

If the phobos logger library doesn't get fixed, maybe you can set up an alternate configuration with a veresioned-in logging facility.

2021-05-29 12:16 UTC, SingingBush commented
I've made changes which I'm pretty happy with and in the end, was actually pretty simple. Not only does this work with both types of loggers but it also retains the module/file/line number that the message came from (which was the main challenge). Basically with this PR, if you want to log something import `mysql.logger` and use one of:

 - logTrace
 - logDebug
 - logInfo
 - logWarn
 - logError
 - logCritical

which are aliases for the underlying logger. There is of course the issue that `std.experimental.logger` is by default set to *LogLevel.all* (https://forum.dlang.org/post/s8r9ac$hlt$1@digitalmars.com) but I think that should be solved in phobos and it's also easy for users to set `sharedLog = new NullLogger()` if really needed. Also at the minute we're not logging much and I suspect most people are using vibe-core, so will not even be affected.

2021-05-31 18:06 UTC, schveiguy commented
I like the way this has changed, this looks much better!

For sure, we can't merge this unless either Phobos is changed or we have this hidden behind a version, or possibly we don't use the shared logger, and allow one to set the logger away from a default Null logger.

One thing I noticed is that you have a third case where neither `Have_vibe_core`, nor `std.experimental.logger` is available, in which case no aliases are defined. I don't think we even need to support this case since we cut off the compiler support to last 10 releases, so most likely you can just say:

```d
version(Have_vibe_core) {
    /* vibe stuff */
}  else {
    /* std.experimental.logger stuff */
}
```

2021-06-01 09:23 UTC, SingingBush commented
> I like the way this has changed, this looks much better!
> 
> For sure, we can't merge this unless either Phobos is changed or we have this hidden behind a version, or possibly we don't use the shared logger, and allow one to set the logger away from a default Null logger.
> 
> One thing I noticed is that you have a third case where neither `Have_vibe_core`, nor `std.experimental.logger` is available, in which case no aliases are defined. I don't think we even need to support this case since we cut off the compiler support to last 10 releases, so most likely you can just say:
> 
> ```d
> version(Have_vibe_core) {
>     /* vibe stuff */
> }  else {
>     /* std.experimental.logger stuff */
> }
> ```

I thought about that but sooner or later std.expirmental.logger will move. When it does it's be nice for it not to break. Hopefully some changes get made before it becomes std.logger

2021-06-01 14:59 UTC, schveiguy commented
> When it does it's be nice for it not to break.

You misunderstand.

If they are not using vibe, and std.experimental.logger doesn't exist, then *no aliases* are defined for the functions. And therefore, when you call the aliases, it will not compile.

But in any case, I'm OK with it breaking, I'd rather know about it loudly! And given that I want to have the library built using the dlang projects buildkite tester, any changes to std.experimental.logger should cause build errors to happen.

2022-01-07 16:39 UTC, schveiguy commented
The issue with std.experimental.logger has been resolved, but not released yet. When that happens, I would like to incorporate this. See https://github.com/dlang/phobos/pull/8336

I want to start working again on getting my safe patch in. If you want this to go in first, let me know.

2022-01-12 21:15 UTC, SingingBush commented
I'd like to get it merged. Not sure how soon I can pick it up though. Perhaps over the weekend. Give me a few days but if I don't get changes in by next week feel free to go first

2022-01-13 14:11 UTC, schveiguy requested changes
You can leave the vibe logging alone, I'll have to look into how the equivalent test harness can be done, but just add that static assert, and I'm good to merge.

2022-01-13 14:11 UTC, schveiguy commented on source/mysql/logger.d
> +		//logFatal("Test that a call to mysql.logger.logFatal maps to vibe.core.log.logFatal");
I can imagine that vibe logger also has customizable logging?

2022-01-13 14:11 UTC, schveiguy commented on source/mysql/logger.d
> +}
I'll say again, we need an `else static assert` here.

2022-01-13 14:15 UTC, schveiguy commented on source/mysql/protocol/comms.d
> +		logError("packet error: %s %s", okp.error, okp.message);
Shouldn't we only log this if there's an error? Or should this be a trace log? I see a lot of "Error: packet error: false" in the output.

2022-01-13 14:42 UTC, schveiguy commented on source/mysql/connection.d
> +		logDebug("opening phobos socket %s:%d", host, port);
For some reason this is using std.experimental.logger even when vibe is used: https://github.com/mysql-d/mysql-native/runs/4796611671?check_suite_focus=true#step:6:991

I'm trying to think of a reason, is the build for one unittest file being done without vibe?

2022-01-13 22:18 UTC, SingingBush commented on source/mysql/protocol/comms.d
> +		logError("packet error: %s %s", okp.error, okp.message);
yep, good spot. that should be in an if statement

2022-01-13 22:43 UTC, SingingBush commented on source/mysql/connection.d
> +		logDebug("opening phobos socket %s:%d", host, port);
it probably is that. It's within the function for opening a socket with phobos which should only be done when vibe-d is not present. the route to opening a socket using the alternative vibe based function requires having gone through a `version(Have_vibe_core)` check on the constructor.

2022-01-14 03:14 UTC, schveiguy commented on source/mysql/connection.d
> +		logDebug("opening phobos socket %s:%d", host, port);
But isn't the vibe test compiled with vibe? How is it that part of the code is built with the vibe version, but part is not? Indeed, most of the logging is vibe, just a few parts aren't, and I'm not sure why.

Phobos sockets can still be used even if you are linking in vibe-core. It's a parameter to the constructor. I would still expect vibe logging if I am using vibe.

Now, technically, I'd like to see the log type be configurable. And really, as said above, it would be best if we used one logging facility and it wrapped the other. But at this point, I just want it to be consistent.

2022-01-14 03:15 UTC, schveiguy commented on source/mysql/connection.d
> +		logDebug("opening phobos socket %s:%d", host, port);
If the solution isn't immediately obvious, then we can just merge this, and I can take a deeper look later. This is after all an issue with unittests, run in the integration subproject, which may not affect the main library.

2022-01-14 03:17 UTC, schveiguy approved these changes

2022-01-14 03:18 UTC, merged

2022-01-14 03:18 UTC, schveiguy commented
tag will have to wait until Phobos is fixed.