Use utf8mb4 by default
mysql-d/mysql-native pull request #220
Opened 2020-10-26 13:23 UTC by kubo39

This commit changes default collation as "utf8mb4_generic_ci" which is
available from MySQL 5.5.3.

2020-10-30 05:07 UTC, kubo39 commented
https://travis-ci.org/github/mysql-d/mysql-native/builds/739867923

2021-01-12 19:11 UTC, schveiguy commented
This looks reasonable to me. I'll get back to this, and probably merge it.

2021-05-24 20:48 UTC, SingingBush commented
@kubo39 please rebase this as there's now a working CI process. It'd be good to see this get merged

2021-05-25 02:26 UTC, schveiguy requested changes

2021-05-25 02:26 UTC, schveiguy commented on source/mysql/protocol/comms.d
> +import std.regex;
I'm hesitant to import regex for the server string translation. Ditto typecons.

At the very least, this needs to be a local import so importing programs don't pay the regex import penalty during compilation.

2021-05-25 02:26 UTC, schveiguy commented on source/mysql/protocol/comms.d
> +	auto patch = captured[3].to!ushort;
Have you thought of using splitter + std.conv.to or std.conv.parse directly?

2021-05-25 02:26 UTC, schveiguy commented on source/mysql/protocol/comms.d
> +	if (mysqlServerVersion >= tuple(5,5,3)) // MySQL >= 5.5.3 supports utf8mb4
How does this work for MariaDB?

2021-05-25 02:28 UTC, schveiguy commented
Also, unittests showing how this check works should be included. I know mysql-native has few true unittests, but this would also help show what this function is supposed to do.

2021-05-25 16:17 UTC, kubo39 commented on source/mysql/protocol/comms.d
> +	if (mysqlServerVersion >= tuple(5,5,3)) // MySQL >= 5.5.3 supports utf8mb4
MariaDB always starts the prefix with "5.5.5-". https://mariadb.com/kb/en/connection/#initial-handshake-packet

2021-05-25 16:18 UTC, kubo39 commented on source/mysql/protocol/comms.d
> +	if (mysqlServerVersion >= tuple(5,5,3)) // MySQL >= 5.5.3 supports utf8mb4
I've added a test for this.

2021-05-25 19:46 UTC, SingingBush reviewed
looks good

2021-05-26 01:00 UTC, schveiguy commented
Ah, this looks much better!

2021-05-26 09:29 UTC, SingingBush commented
> Ah, this looks much better!

I think for this to be merged you may need to complete the review process to confirm the requested changes are complete.

2021-05-28 15:34 UTC, schveiguy approved these changes

2021-05-28 15:56 UTC, schveiguy commented
Reopened to trigger CI

2021-05-28 16:13 UTC, merged